# Makefile for rusticOS - bootloader, loader, and 32-bit kernel

.PHONY: all clean distclean run

# Tools
NASM := nasm
DD := dd
QEMU := qemu-system-x86_64
CC := gcc
CXX := g++
LD := ld
OBJCOPY := objcopy

# Directories
BOOT_DIR := boot
SRC_DIR := src
BUILD_DIR := build

# Compiler flags for 32-bit kernel
CFLAGS := -m32 -ffreestanding -fno-pic -fno-pie -fno-stack-protector -O2
CXXFLAGS := -m32 -ffreestanding -fno-pic -fno-pie -fno-stack-protector -O2 -fno-exceptions -fno-rtti
ASFLAGS := -m32
LDFLAGS := -m elf_i386 -static -T linker.ld

# Source files
KERNEL_SOURCES := $(SRC_DIR)/kernel.cpp $(SRC_DIR)/terminal.cpp $(SRC_DIR)/keyboard.cpp \
                  $(SRC_DIR)/command.cpp $(SRC_DIR)/filesystem.cpp $(SRC_DIR)/virtual_disk.cpp \
                  $(SRC_DIR)/cxxabi.cpp
KERNEL_ASM := $(SRC_DIR)/crt0.s
KERNEL_OBJS := $(BUILD_DIR)/crt0.o $(patsubst $(SRC_DIR)/%.cpp,$(BUILD_DIR)/%.o,$(KERNEL_SOURCES))

BOOTLOADER_SRC := $(BOOT_DIR)/bootloader.asm
LOADER_SRC := $(BOOT_DIR)/loader.asm

BOOTLOADER_BIN := $(BUILD_DIR)/bootloader.bin
LOADER_BIN := $(BUILD_DIR)/loader.bin
KERNEL_ELF := $(BUILD_DIR)/kernel.elf
KERNEL_BIN := $(BUILD_DIR)/kernel.bin
DISK_IMG := $(BUILD_DIR)/disk.img

# Kernel size (computed at build time)
KERNEL_SIZE_BYTES = $(shell stat -c%s $(KERNEL_BIN) 2>/dev/null || echo 0)
KERNEL_SECTORS = $(shell awk 'BEGIN {print int(($(KERNEL_SIZE_BYTES)+511)/512)}')

# Create build directory
$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

# Compile C++ sources to object files
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
	@echo "Compiling $<..."
	@$(CXX) $(CXXFLAGS) -c $< -o $@

# Assemble crt0.s (AT&T syntax, 32-bit)
$(BUILD_DIR)/crt0.o: $(SRC_DIR)/crt0.s | $(BUILD_DIR)
	@echo "Assembling $<..."
	@as --32 $< -o $@

# Link kernel to an ELF
$(KERNEL_ELF): $(KERNEL_OBJS) | $(BUILD_DIR)
	@echo "Linking kernel (ELF)..."
	@$(LD) $(LDFLAGS) -o $@ $(KERNEL_OBJS)
	@echo "Kernel ELF size: $$(stat -c%s $@) bytes"

# Produce flat binary from the ELF (this is the file used on disk)
$(KERNEL_BIN): $(KERNEL_ELF) | $(BUILD_DIR)
	@echo "Generating flat kernel binary $@..."
	@$(OBJCOPY) -O binary $(KERNEL_ELF) $@
	@echo "Kernel binary size: $$(stat -c%s $@) bytes"

# generate NASM include with kernel size and sector count (placed where ASM expects it)
boot/kernel_sectors.inc: $(KERNEL_BIN) | $(BUILD_DIR)
	@echo "Generating $@ from $(KERNEL_BIN)..."
	@size=$$(stat -c%s $(KERNEL_BIN)); \
	sectors=$$(( (size + 511) / 512 )); \
	printf "; Autogenerated by Makefile - do not edit\n" > $@; \
	printf "%%assign KERNEL_SIZE_BYTES %s\n" $$size >> $@; \
	printf "%%assign KERNEL_SECTORS %s\n" $$sectors >> $@; \
	printf "%%assign LOADER_SECTORS 2\n" >> $@

# generate NASM include with loader size and sector count (placed where ASM expects it)
boot/loader_sectors.inc: $(LOADER_BIN) | $(BUILD_DIR)
	@echo "Generating $@ from $(LOADER_BIN)..."
	@size=$$(stat -c%s $(LOADER_BIN)); \
	sectors=$$(( (size + 511) / 512 )); \
	printf "; Autogenerated by Makefile - do not edit\n" > $@; \
	printf "%%assign LOADER_SIZE_BYTES %s\n" $$size >> $@; \
	printf "%%assign LOADER_SECTORS %s\n" $$sectors >> $@

# ensure bootloader assembles after generated include
$(BOOTLOADER_BIN): $(BOOTLOADER_SRC) boot/kernel_sectors.inc boot/loader_sectors.inc | $(BUILD_DIR)
	@echo "Assembling bootloader..."
	@$(NASM) -f bin -o $@ $<

# Assemble loader (use generated include)
$(LOADER_BIN): $(LOADER_SRC) boot/kernel_sectors.inc | $(BUILD_DIR)
	@echo "Assembling loader..."
	@$(NASM) -f bin -o $@ $<

# Create disk image
$(DISK_IMG): $(BOOTLOADER_BIN) $(LOADER_BIN) $(KERNEL_BIN) | $(BUILD_DIR)
	@echo "Creating disk image..."
	@$(DD) if=/dev/zero of=$@ bs=512 count=256 2>/dev/null
	@$(DD) if=$(BOOTLOADER_BIN) of=$@ bs=512 seek=0 conv=notrunc 2>/dev/null
	@$(DD) if=$(LOADER_BIN) of=$@ bs=512 seek=1 conv=notrunc 2>/dev/null
	@$(DD) if=$(KERNEL_BIN) of=$@ bs=512 seek=2 conv=notrunc 2>/dev/null
	@echo "Disk image created: $@"

# Build all
all: $(DISK_IMG)

# Run in QEMU
run: $(DISK_IMG)
	$(QEMU) -drive format=raw,file=$< -m 512M -serial stdio

# Clean build files
clean:
	@rm -rf $(BUILD_DIR) boot/kernel_sectors.inc
	@rm -f $(KERNEL_ELF)

# Distclean (remove everything)
distclean: clean
	@rm -f $(SRC_DIR)/*.o