[org 0x7c00]
[bits 16]

%include "boot/kernel_sectors.inc"
%include "boot/loader_sectors.inc"   ; autogenerated by Makefile

%ifndef LOADER_SECTORS
%assign LOADER_SECTORS 4        ; increased default (was 2)
%endif

start:
    cli
    mov ax, 0x0000
    mov ds, ax
    mov es, ax
    mov ss, ax
    mov sp, 0x7c00
    sti

    mov si, msg_loading
    call print_string

    ; Load loader: CHS sector 2 (= LBA 1) into 0x1000:0x0000
    mov ah, 0x02
    mov al, LOADER_SECTORS
    mov ch, 0
    mov cl, 2
    mov dh, 0
    mov ax, 0x1000
    mov es, ax
    xor bx, bx
    int 0x13
    jc .load_error

    mov si, msg_loaded
    call print_string

    mov si, msg_jumping
    call print_string

    ; Jump to loader
    jmp 0x1000:0x0000

.load_error:
    ; show AH status and halt (unchanged)
    push ax
    mov bl, ah
    mov al, bl
    and al, 0x0F
    cmp al, 10
    jl .L1
    add al, 'A' - 10
    jmp .L1done
.L1:
    add al, '0'
.L1done:
    mov bh, bl
    shr bh, 4
    and bh, 0x0F
    cmp bh, 10
    jl .H1
    add bh, 'A' - 10
    jmp .H1done
.H1:
    add bh, '0'
.H1done:
    push es
    mov ax, 0xB800
    mov es, ax
    xor di, di
    mov [es:di], al
    mov byte [es:di+1], 0x07
    mov [es:di+2], bh
    mov byte [es:di+3], 0x07
    pop es
    pop ax
.halt:
    cli
    hlt
    jmp .halt

print_string:
    mov ah, 0x0E
.loop:
    lodsb
    test al, al
    jz .done
    int 0x10
    jmp .loop
.done:
    ret

msg_loading: db "[MBR] Loading loader...", 0x0D,0x0A,0
msg_loaded:  db "[MBR] Loader loaded", 0x0D,0x0A,0
msg_jumping: db "[MBR] Jumping to loader", 0x0D,0x0A,0

times (512 - 2 - ($-$$)) db 0
dw 0xAA55